package dsl

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"

	canonical "github.com/paradigm-terra/canonical-go"
)

// Byte-for-byte parity against the TypeScript reference golden vectors.
//
// Loads the committed ../dsl/vectors/golden.json (generated by the TS reference
// @paradigm-terra/dsl) and verifies that this package reproduces every
// evaluation outcome + reason sub-code and every DSL_HASH exactly. This is the
// parity evidence needed to promote the vectors to NORMATIVE.

type goldenDoc struct {
	Vectors []struct {
		ID                string `json:"id"`
		Scope             string `json:"scope"`
		Version           string `json:"version"`
		ExprCanonical     string `json:"expr_canonical"`
		BindingsCanonical string `json:"bindings_canonical"`
		Output            struct {
			Outcome string `json:"outcome"`
			Reason  string `json:"reason"`
			DslHash string `json:"dsl_hash"`
		} `json:"output"`
	} `json:"vectors"`
	CrossVersion struct {
		ExprCanonical string `json:"expr_canonical"`
		H11           string `json:"dsl_hash_v1_1"`
		H12           string `json:"dsl_hash_v1_2"`
	} `json:"cross_version"`
	EmergencyInvariants []struct {
		ExprCanonical string `json:"expr_canonical"`
		DslHash       string `json:"dsl_hash"`
	} `json:"emergency_invariants"`
}

func hexHash(h [32]byte) string { return "0x" + hex.EncodeToString(h[:]) }

func TestParityWithTypeScriptGoldenVectors(t *testing.T) {
	data, err := os.ReadFile("../dsl/vectors/golden.json")
	if err != nil {
		t.Fatalf("read golden.json: %v", err)
	}
	var doc goldenDoc
	if err := json.Unmarshal(data, &doc); err != nil {
		t.Fatalf("parse golden.json: %v", err)
	}
	if len(doc.Vectors) < 28 {
		t.Fatalf("expected >=28 vectors, got %d", len(doc.Vectors))
	}

	checks := 0
	for _, v := range doc.Vectors {
		scope, ok := ScopeFromString(v.Scope)
		if !ok {
			t.Fatalf("%s: bad scope %q", v.ID, v.Scope)
		}
		version, ok := VersionFromString(v.Version)
		if !ok {
			t.Fatalf("%s: bad version %q", v.ID, v.Version)
		}
		expr, perr := canonical.ParseCanonical(v.ExprCanonical)
		if perr != nil {
			t.Fatalf("%s: parse expr: %v", v.ID, perr)
		}
		var bindings Bindings
		if v.BindingsCanonical != "" {
			bj, berr := canonical.ParseCanonical(v.BindingsCanonical)
			if berr != nil {
				t.Fatalf("%s: parse bindings: %v", v.ID, berr)
			}
			bindings = BindingsFromJcs(bj)
		}

		out := Run(expr, scope, version, bindings)
		checks++
		if out.Code != v.Output.Outcome {
			t.Errorf("%s.outcome: got %s want %s", v.ID, out.Code, v.Output.Outcome)
		}
		if out.Reason != v.Output.Reason {
			t.Errorf("%s.reason: got %q want %q", v.ID, out.Reason, v.Output.Reason)
		}

		h, herr := DslHash(expr, version)
		if herr != nil {
			t.Fatalf("%s: hash: %v", v.ID, herr)
		}
		checks++
		if got := hexHash(h); got != v.Output.DslHash {
			t.Errorf("%s.dsl_hash: got %s want %s", v.ID, got, v.Output.DslHash)
		}
	}

	// cross-version
	cvExpr, _ := canonical.ParseCanonical(doc.CrossVersion.ExprCanonical)
	for _, tc := range []struct {
		ver  Version
		want string
	}{{V11, doc.CrossVersion.H11}, {V12, doc.CrossVersion.H12}} {
		h, _ := DslHash(cvExpr, tc.ver)
		checks++
		if got := hexHash(h); got != tc.want {
			t.Errorf("cross_version: got %s want %s", got, tc.want)
		}
	}

	// emergency invariants
	for i, e := range doc.EmergencyInvariants {
		expr, _ := canonical.ParseCanonical(e.ExprCanonical)
		h, _ := DslHash(expr, V12)
		checks++
		if got := hexHash(h); got != e.DslHash {
			t.Errorf("emergency[%d].dsl_hash: got %s want %s", i, got, e.DslHash)
		}
	}

	if !t.Failed() {
		t.Logf("All %d parity checks passed against TypeScript golden vectors.", checks)
	}
}
