package canonical

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"strconv"
	"strings"
	"testing"
)

// Byte-for-byte parity against the TypeScript reference golden vectors.
//
// Loads the committed ../canonical/vectors/golden.json (generated by the TS
// implementation) and independently recomputes every vector with this package,
// asserting each recorded byte string / hash matches. A green run is the Go
// half of the parity evidence needed to promote the vectors to NORMATIVE.

type vectorDoc struct {
	Vectors []vectorEntry `json:"vectors"`
}

type vectorEntry struct {
	ID     string            `json:"id"`
	Input  map[string]any    `json:"input"`
	Output map[string]string `json:"output"`
}

func hexp(b []byte) string { return "0x" + hex.EncodeToString(b) }

func fill32(b byte) [32]byte {
	var a [32]byte
	for i := range a {
		a[i] = b
	}
	return a
}

func TestParityWithTypeScriptGoldenVectors(t *testing.T) {
	data, err := os.ReadFile("../canonical/vectors/golden.json")
	if err != nil {
		t.Fatalf("read golden.json: %v", err)
	}
	var doc vectorDoc
	if err := json.Unmarshal(data, &doc); err != nil {
		t.Fatalf("parse golden.json: %v", err)
	}
	byID := make(map[string]vectorEntry, len(doc.Vectors))
	for _, v := range doc.Vectors {
		byID[v.ID] = v
	}

	checks := 0
	var fails []string
	expect := func(id, field, actual string) {
		checks++
		v, ok := byID[id]
		if !ok {
			fails = append(fails, id+": missing vector")
			return
		}
		exp, ok := v.Output[field]
		if !ok {
			fails = append(fails, id+"."+field+": field missing in golden.json")
			return
		}
		if exp != actual {
			fails = append(fails, id+"."+field+"\n    expected: "+exp+"\n    actual:   "+actual)
		}
	}
	inputStr := func(id, key string) string {
		s, _ := byID[id].Input[key].(string)
		return s
	}
	must := func(b []byte, err error) []byte {
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		return b
	}
	cv := func(v Value) []byte { return must(CanonicalizeValue(v)) }

	// ---------- integers ----------
	for _, id := range []string{"int256_zero", "int256_minus_one", "int256_min", "int256_max"} {
		b, err := EncodeInt256Dec(inputStr(id, "value"))
		if err != nil {
			t.Fatalf("%s: %v", id, err)
		}
		expect(id, "bytes_hex", hexp(b[:]))
		if id == "int256_zero" || id == "int256_minus_one" {
			s := SHA256(b[:])
			expect(id, "sha256", hexp(s[:]))
		}
	}
	{
		b, err := EncodeUint256Dec(inputStr("uint256_max", "value"))
		if err != nil {
			t.Fatalf("uint256_max: %v", err)
		}
		expect("uint256_max", "bytes_hex", hexp(b[:]))
	}
	{
		val := inputStr("uint64_sequence", "value")
		n, err := strconv.ParseUint(strings.TrimPrefix(val, "0x"), 16, 64)
		if err != nil {
			t.Fatalf("uint64_sequence: %v", err)
		}
		b := EncodeUint64(n)
		expect("uint64_sequence", "bytes_hex", hexp(b[:]))
	}

	// ---------- UTF-8 NFC ----------
	{
		decomposed := "é" // e + combining acute
		composed := "é"
		nfc := must(UTF8NFCBytes(decomposed))
		expect("utf8_nfc_e_acute", "bytes_hex", hexp(nfc))
		s := SHA256(nfc)
		expect("utf8_nfc_e_acute", "sha256", hexp(s[:]))
		comp := must(UTF8NFCBytes(composed))
		expect("utf8_nfc_e_acute", "composed_bytes_hex", hexp(comp))
	}

	// ---------- TON address ----------
	{
		addr := inputStr("ton_address_canonical", "address")
		b := must(AddressToBytes(addr))
		expect("ton_address_canonical", "address_bytes_hex", hexp(b))
		h, err := DomainHash(AddressV1, b)
		if err != nil {
			t.Fatalf("address domain hash: %v", err)
		}
		expect("ton_address_canonical", "domain_hash", hexp(h[:]))
	}

	// ---------- JCS ----------
	{
		canon := must(CanonicalizeString(inputStr("jcs_sample_b2_a1", "json")))
		expect("jcs_sample_b2_a1", "canonical_utf8_hex", hexp(canon))
		expect("jcs_sample_b2_a1", "canonical_text", string(canon))
		s := SHA256(canon)
		expect("jcs_sample_b2_a1", "sha256", hexp(s[:]))
	}
	{
		canon := must(CanonicalizeString(inputStr("dsl_expr_gte_x_0", "expression")))
		expect("dsl_expr_gte_x_0", "canonical_text", string(canon))
		h1, _ := DomainHash(DSLV11, canon)
		expect("dsl_expr_gte_x_0", "dsl_v1_1_hash", hexp(h1[:]))
		h2, _ := DomainHash(DSLV12, canon)
		expect("dsl_expr_gte_x_0", "dsl_v1_2_hash", hexp(h2[:]))
	}
	{
		canon := must(CanonicalizeString(inputStr("jcs_big_integer", "json")))
		expect("jcs_big_integer", "canonical_text", string(canon))
		s := SHA256(canon)
		expect("jcs_big_integer", "sha256", hexp(s[:]))
	}

	// ---------- CAL (canonicalize value + domain hash) ----------
	{
		cal := O(
			P("action", "wallet.send_ton"),
			P("agent_id", "0:83dfd552e63729b472fc4e4a8f8f83d4a8f4f3a3e3e3a3e3e3a3e3e3a3e3e3a3"),
			P("cal_version", "0.1.0"),
			P("expiration_tick", IntU(1050000)),
			P("nonce", IntU(42)),
			P("preconditions", O(
				P("op", "eq"),
				P("lhs", O(P("var", "x"))),
				P("rhs", O(P("const", IntU(1)))),
			)),
			P("receipt_required", true),
		)
		b := cv(cal)
		expect("cal_v1_hash_example", "canonical_text", string(b))
		h, _ := DomainHash(CALV1, b)
		expect("cal_v1_hash_example", "cal_hash", hexp(h[:]))
	}

	// ---------- Merkle: stream tree ----------
	{
		root, err := StreamTreeRoot([]StreamLeaf{
			{StreamID: "treasury", StateHash: fill32(0xaa), LastEventHash: fill32(0xbb), LastSeqno: 100},
			{StreamID: "registry", StateHash: fill32(0x11), LastEventHash: fill32(0x22), LastSeqno: 7},
		})
		if err != nil {
			t.Fatalf("stream tree: %v", err)
		}
		expect("merkle_stream_tree_2", "root", hexp(root[:]))
	}

	// ---------- Merkle: 3 leaves, odd duplication ----------
	{
		a := SHA256([]byte("A"))
		b := SHA256([]byte("B"))
		c := SHA256([]byte("C"))
		root, err := BinaryMerkle([][32]byte{a, b, c}, MerkleNodeV1)
		if err != nil {
			t.Fatalf("3-leaf merkle: %v", err)
		}
		expect("merkle_three_leaves_odd_duplicate", "root", hexp(root[:]))
	}

	// ---------- State root (CAL Spec §7.3) ----------
	{
		namespaces := []StateNamespace{
			{Name: "state.cal", CanonicalBytes: cv(O(
				P("nonces", O()),
				P("in_flight", O()),
			))},
			{Name: "state.failure_mode", CanonicalBytes: cv(O(
				P("current", "NORMAL"),
				P("entered_at", IntU(0)),
				P("recovery_progress", IntU(0)),
				P("is_bounded_mode", false),
				P("capture_guard_counters", O()),
			))},
			{Name: "state.governance", CanonicalBytes: cv(O(
				P("slots", O()),
				P("active_proposals", A()),
				P("cartel_flags", O()),
				P("cluster_detection", O()),
				P("proposal_votes", O()),
				P("gas_price_nano_ptra_per_unit", IntU(1000)),
			))},
			{Name: "state.oracles", CanonicalBytes: cv(O(
				P("nodes", O()),
				P("feeds", O()),
				P("slashed_nodes", O()),
			))},
			{Name: "state.ptra", CanonicalBytes: cv(O(
				P("total_supply", IntU(1000000000000000000)),
				P("burned_total", IntU(0)),
				P("burned_window", IntU(0)),
				P("twap_ton_ratio", IntU(0)),
				P("stakes", O()),
				P("balances", O()),
			))},
			{Name: "state.registry", CanonicalBytes: cv(O(
				P("agents", O()),
				P("mcp_schema_hash", "0x"+strings.Repeat("00", 32)),
				P("protocols", O()),
			))},
			{Name: "state.tick", CanonicalBytes: cv(O(
				P("current", IntU(0)),
				P("genesis", IntU(0)),
				P("blocks_per_tick", IntU(12)),
				P("epoch", IntU(0)),
			))},
			{Name: "state.treasury", CanonicalBytes: cv(O(
				P("nav", IntU(0)),
				P("outflow_window", IntU(0)),
				P("developer_fund_balance", IntU(0)),
				P("staking_pool", IntU(0)),
				P("slot_pool", IntU(0)),
				P("collected_fees_window", IntU(0)),
			))},
		}
		root, err := StateRoot(namespaces)
		if err != nil {
			t.Fatalf("state root: %v", err)
		}
		expect("state_root_genesis_empty", "root", hexp(root[:]))
		expect("state_root_genesis_empty", "domain_tag", StateRootV1)
	}

	// ---------- Framing ----------
	{
		typeTag, _ := strconv.ParseUint(strings.TrimPrefix(inputStr("frame_hello", "type_tag"), "0x"), 16, 16)
		version, _ := strconv.ParseUint(strings.TrimPrefix(inputStr("frame_hello", "version"), "0x"), 16, 16)
		payload := inputStr("frame_hello", "payload_utf8")
		frame := must(EncodeFrame(uint16(typeTag), uint16(version), []byte(payload)))
		expect("frame_hello", "frame_hex", hexp(frame))
	}

	// ---------- Domain tag registry ----------
	for _, tag := range AllDomainTags {
		h, err := DomainHash(tag.Value, nil)
		if err != nil {
			t.Fatalf("domain hash %s: %v", tag.Name, err)
		}
		expect("domain_tags_registry", tag.Name, "sha256(empty||tag)="+hexp(h[:]))
	}

	// ---------- Report ----------
	if len(fails) > 0 {
		t.Fatalf("%d of %d parity checks failed:\n\n%s", len(fails), checks, strings.Join(fails, "\n\n"))
	}
	t.Logf("All %d parity checks passed against TypeScript golden vectors.", checks)
}
