//! Byte-for-byte parity against the TypeScript reference golden vectors.
//!
//! Loads the committed `../dsl/vectors/golden.json` (generated by the TS
//! reference `@paradigm-terra/dsl`) and verifies that this crate reproduces
//! every evaluation outcome + reason sub-code and every DSL_HASH exactly. This
//! is the parity evidence needed to promote the vectors to NORMATIVE.

use paradigm_terra_canonical::jcs::parse_canonical;
use paradigm_terra_dsl::{dsl_hash, run, Bindings, Scope, Version};

const GOLDEN: &str = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/../dsl/vectors/golden.json"));

fn hex32(b: &[u8; 32]) -> String {
    let mut s = String::with_capacity(66);
    s.push_str("0x");
    for byte in b {
        s.push_str(&format!("{byte:02x}"));
    }
    s
}

#[test]
fn parity_with_typescript_golden_vectors() {
    let doc = parse_canonical(GOLDEN).expect("parse golden.json");
    let mut fails: Vec<String> = Vec::new();
    let mut checks = 0usize;

    // ---- vectors: outcome + reason + hash ----
    let vectors = doc.get("vectors").and_then(|v| v.as_array()).expect("vectors[]");
    for v in vectors {
        let id = v.get("id").and_then(|x| x.as_str()).unwrap_or("<no id>");
        let scope = Scope::from_str(v.get("scope").and_then(|x| x.as_str()).unwrap()).expect("scope");
        let version = Version::from_str(v.get("version").and_then(|x| x.as_str()).unwrap()).expect("version");
        let expr = parse_canonical(v.get("expr_canonical").and_then(|x| x.as_str()).unwrap()).expect("expr");

        let bindings = match v.get("bindings_canonical").and_then(|x| x.as_str()) {
            Some(text) => Bindings::from_jcs(&parse_canonical(text).expect("bindings")),
            None => Bindings::default(),
        };

        let out = run(&expr, scope, version, &bindings);
        let output = v.get("output").expect("output");
        let want_code = output.get("outcome").and_then(|x| x.as_str()).unwrap();
        let want_reason = output.get("reason").and_then(|x| x.as_str());

        checks += 1;
        if out.code != want_code {
            fails.push(format!("{id}.outcome: got {} want {}", out.code, want_code));
        }
        if out.reason.as_deref() != want_reason {
            fails.push(format!("{id}.reason: got {:?} want {:?}", out.reason, want_reason));
        }

        let got_hash = hex32(&dsl_hash(&expr, version).expect("hash"));
        let want_hash = output.get("dsl_hash").and_then(|x| x.as_str()).unwrap();
        checks += 1;
        if got_hash != want_hash {
            fails.push(format!("{id}.dsl_hash: got {got_hash} want {want_hash}"));
        }
    }

    // ---- cross-version hashes ----
    let cv = doc.get("cross_version").expect("cross_version");
    let cv_expr = parse_canonical(cv.get("expr_canonical").and_then(|x| x.as_str()).unwrap()).unwrap();
    for (ver, key) in [(Version::V11, "dsl_hash_v1_1"), (Version::V12, "dsl_hash_v1_2")] {
        let got = hex32(&dsl_hash(&cv_expr, ver).unwrap());
        let want = cv.get(key).and_then(|x| x.as_str()).unwrap();
        checks += 1;
        if got != want {
            fails.push(format!("cross_version.{key}: got {got} want {want}"));
        }
    }

    // ---- emergency invariants ----
    let emergency = doc.get("emergency_invariants").and_then(|v| v.as_array()).expect("emergency[]");
    for e in emergency {
        let expr = parse_canonical(e.get("expr_canonical").and_then(|x| x.as_str()).unwrap()).unwrap();
        let got = hex32(&dsl_hash(&expr, Version::V12).unwrap());
        let want = e.get("dsl_hash").and_then(|x| x.as_str()).unwrap();
        checks += 1;
        if got != want {
            fails.push(format!("emergency.dsl_hash: got {got} want {want}"));
        }
    }

    if !fails.is_empty() {
        panic!("{} parity failures:\n{}", fails.len(), fails.join("\n"));
    }
    println!("All {checks} parity checks passed against TypeScript golden vectors.");
}

#[test]
fn matches_vector_count() {
    let doc = parse_canonical(GOLDEN).unwrap();
    let n = doc.get("vectors").and_then(|v| v.as_array()).unwrap().len();
    assert!(n >= 28, "expected >=28 vectors, got {n}");
}
