/**
 * Generate golden vectors for @paradigm-terra/orchestrator v0.1.0.
 *
 * Pins, per program: the canonical start state + each submission's canonical CAL and
 * trace (so a Rust/Go port reproduces the same run), and the expected output — the
 * full canonical event log, per-tick STATE_ROOT + CE §6.3 global Merkle root, each
 * submission's terminal stage / reason / per-event STATE_ROOTs, and the final root.
 * NORMATIVE: the Rust (orchestrator-rs) and Go (orchestrator-go) ports reproduce
 * every value byte-for-byte.
 */

import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { serializeCanonical, type JcsValue } from "@paradigm-terra/canonical";
import type { ExecutionTrace } from "@paradigm-terra/cal-validator";
import { run, type Submission } from "../src/index.js";
import { PROGRAMS } from "./programs.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = resolve(__dirname, "..", "vectors", "golden.json");

function traceToJcs(t: ExecutionTrace): JcsValue {
  return {
    current_tick: t.currentTick,
    owner_sig_present: t.ownerSigPresent,
    state_before: t.stateBefore as JcsValue,
    state_after: t.stateAfter as JcsValue,
    steps: t.steps.map((s): JcsValue => {
      const o: { [k: string]: JcsValue } = { ok: s.ok, effects: [...s.effects] as JcsValue[] };
      if (s.errorDetail !== undefined) o["error_detail"] = s.errorDetail;
      return o;
    }),
  };
}

function subToJcs(s: Submission): JcsValue {
  return { cal_canonical: serializeCanonical(s.cal as JcsValue), trace_canonical: serializeCanonical(traceToJcs(s.trace)) };
}

const programs = PROGRAMS.map(({ id, description, program }) => {
  const t = run(program);
  return {
    id,
    description,
    start_state_canonical: serializeCanonical(t.genesisState as JcsValue),
    input_ticks: program.ticks.map((blk) => ({ tick: blk.tick.toString(), submissions: blk.submissions.map(subToJcs) })),
    expected: {
      event_log: t.eventLog.map((e) => serializeCanonical(e as JcsValue)),
      final_state_root: t.finalStateRoot,
      ticks: t.ticks.map((tk) => ({
        tick: tk.tick.toString(),
        state_root: tk.stateRoot,
        global_merkle_root: tk.globalMerkleRoot,
        submissions: tk.submissions.map((s) => ({
          cal_hash: s.calHash,
          agent_id: s.agentId,
          terminal_stage: s.terminalStage,
          reason_code: s.reasonCode,
          event_types: s.events.map((e) => e["event_type"] as string),
          state_roots: s.stateRoots,
          ingress_error: s.ingressError ?? null,
        })),
      })),
    },
  };
});

const doc = {
  meta: {
    package: "@paradigm-terra/orchestrator",
    version: "0.1.0",
    spec_basis:
      "CAL Execution Specification v0.1.0-draft §6 (per-agent serialization & nonce), §7 (reducer & STATE_ROOT) + Canonical Encoding v1.3 §6.3 (global stream Merkle root). The node folds per-tick {cal, trace} submissions through cal.created/cal.signed (ingress) -> validate() -> apply(), recording STATE_ROOT per event and the global Merkle root per tick; the event log is replayable from start_state. v0.1.0 models one canonical stream (\"global\"). EXPIRED_POST/AGENT_BUSY need a staged validator (atomic validate cannot reach them) — deferred.",
    generated_at: new Date().toISOString(),
    status:
      "NORMATIVE — generated by the TypeScript reference implementation and verified byte-for-byte by the Rust (orchestrator-rs) and Go (orchestrator-go) parity implementations on 2026-05-27 (every event-log entry, per-tick STATE_ROOT and CE §6.3 global stream Merkle root, terminal stage, reason code, and per-event STATE_ROOTs). EXPIRED_POST/AGENT_BUSY remain unreachable under the atomic validate() model and are a deferred staged-validator increment (the golden pins everything the atomic model can express).",
  },
  programs,
};

await writeFile(OUTPUT_PATH, JSON.stringify(doc, null, 2) + "\n", "utf8");
console.log(`Wrote ${programs.length} orchestrator programs to ${OUTPUT_PATH}`);
