// Generator: emit the "assigned as of Unicode 15.1" code-point range table into
// all three reference implementations (TS / Rust / Go) from a single source —
// the official UCD 15.1.0 DerivedAge.txt.
//
// Rationale (CE v1.3 §3.2, domain restriction): the three NFC backends use
// different Unicode versions (Go x/text = 15.0, Node ICU / Rust = 17.0). By the
// Unicode Normalization Stability Policy, NFC is identical across versions for
// any string whose code points were all assigned in the pinned version. So a
// canonical string MUST contain only code points assigned as of Unicode 15.1;
// "too-new" code points (e.g. the 46 combining marks added in 16.0/17.0) are
// rejected as NONCANONICAL_EVENT, and every accepted string normalizes
// identically in all three backends with no backend changes.
//
// DerivedAge.txt lists, for every code point, the Unicode version in which it
// was first assigned. Because we fetch the *15.1.0* edition, every code point it
// lists is assigned as of 15.1; the union of all its ranges is exactly the
// accepted set. (Surrogates/noncharacters appear in DerivedAge but are inert
// here — valid UTF-8 scalars never include surrogates, and the check only ever
// runs on real scalars.)
//
// Usage: node tools/gen_assigned.mjs
// Re-run only to regenerate; the emitted files are committed.

import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");
const SRC = resolve(HERE, "DerivedAge-15.1.0.txt");
const UNICODE_VERSION = "15.1";

// ---- parse ---------------------------------------------------------------
const text = readFileSync(SRC, "utf8");
const raw = [];
for (const line of text.split("\n")) {
  const hash = line.indexOf("#");
  const body = (hash >= 0 ? line.slice(0, hash) : line).trim();
  if (!body) continue;
  const semi = body.indexOf(";");
  const field = (semi >= 0 ? body.slice(0, semi) : body).trim();
  const m = /^([0-9A-Fa-f]+)(?:\.\.([0-9A-Fa-f]+))?$/.exec(field);
  if (!m) continue;
  const lo = parseInt(m[1], 16);
  const hi = m[2] ? parseInt(m[2], 16) : lo;
  raw.push([lo, hi]);
}

// ---- merge sorted ranges -------------------------------------------------
raw.sort((a, b) => a[0] - b[0]);
const ranges = [];
for (const [lo, hi] of raw) {
  if (ranges.length && lo <= ranges[ranges.length - 1][1] + 1) {
    ranges[ranges.length - 1][1] = Math.max(ranges[ranges.length - 1][1], hi);
  } else {
    ranges.push([lo, hi]);
  }
}

const count = ranges.reduce((n, [lo, hi]) => n + (hi - lo + 1), 0);
// canonical fingerprint of the merged data, embedded into all three files
const canon = ranges.map(([lo, hi]) => `${lo.toString(16)}-${hi.toString(16)}`).join(",");
const sha = createHash("sha256").update(canon).digest("hex");
console.log(`parsed ${raw.length} lines -> ${ranges.length} merged ranges, ${count} assigned code points`);
console.log(`sha256(ranges) = ${sha}`);

const provenance =
  `Unicode ${UNICODE_VERSION} assigned code points (UCD 15.1.0 DerivedAge.txt).\n` +
  `Generated by tools/gen_assigned.mjs — DO NOT EDIT BY HAND.\n` +
  `${ranges.length} ranges, ${count} code points. sha256(ranges)=${sha}`;

// ---- emit TypeScript -----------------------------------------------------
{
  const flat = ranges.flat();
  const body = `// ${provenance.split("\n").join("\n// ")}
//
// A canonical string MUST contain only code points assigned as of Unicode
// ${UNICODE_VERSION} (CE v1.3 §3.2). This makes NFC identical across the TS/Rust/Go
// backends despite their differing Unicode versions (Normalization Stability).

// Flat, sorted, inclusive ranges: [lo0, hi0, lo1, hi1, ...].
const RANGES: readonly number[] = [
${chunk(flat.map(String), 12).map((r) => "  " + r.join(", ") + ",").join("\n")}
];

export const UNICODE_ASSIGNED_VERSION = "${UNICODE_VERSION}";
export const UNICODE_ASSIGNED_SHA256 = "${sha}";

/** True iff \`cp\` is a Unicode scalar assigned as of Unicode ${UNICODE_VERSION}. */
export function isAssignedCodePoint(cp: number): boolean {
  let lo = 0;
  let hi = RANGES.length / 2 - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    const rlo = RANGES[mid * 2]!;
    const rhi = RANGES[mid * 2 + 1]!;
    if (cp < rlo) hi = mid - 1;
    else if (cp > rhi) lo = mid + 1;
    else return true;
  }
  return false;
}
`;
  writeFileSync(resolve(ROOT, "canonical/src/unicodeAssigned.ts"), body);
}

// ---- emit Rust -----------------------------------------------------------
{
  const pairs = ranges.map(([lo, hi]) => `(0x${lo.toString(16)}, 0x${hi.toString(16)})`);
  const body = `// ${provenance.split("\n").join("\n// ")}
//
// A canonical string MUST contain only code points assigned as of Unicode
// ${UNICODE_VERSION} (CE v1.3 §3.2). This makes NFC identical across the TS/Rust/Go
// backends despite their differing Unicode versions (Normalization Stability).

pub const UNICODE_ASSIGNED_VERSION: &str = "${UNICODE_VERSION}";
pub const UNICODE_ASSIGNED_SHA256: &str = "${sha}";

// Sorted, inclusive (lo, hi) ranges.
static RANGES: &[(u32, u32)] = &[
${chunk(pairs, 6).map((r) => "    " + r.join(", ") + ",").join("\n")}
];

/// True iff \`cp\` is a Unicode scalar assigned as of Unicode ${UNICODE_VERSION}.
pub fn is_assigned_code_point(cp: u32) -> bool {
    RANGES
        .binary_search_by(|&(lo, hi)| {
            if cp < lo {
                std::cmp::Ordering::Greater
            } else if cp > hi {
                std::cmp::Ordering::Less
            } else {
                std::cmp::Ordering::Equal
            }
        })
        .is_ok()
}
`;
  writeFileSync(resolve(ROOT, "canonical-rs/src/unicode_assigned.rs"), body);
}

// ---- emit Go -------------------------------------------------------------
{
  const pairs = ranges.map(([lo, hi]) => `{0x${lo.toString(16)}, 0x${hi.toString(16)}}`);
  const body = `package canonical

// ${provenance.split("\n").join("\n// ")}
//
// A canonical string MUST contain only code points assigned as of Unicode
// ${UNICODE_VERSION} (CE v1.3 §3.2). This makes NFC identical across the TS/Rust/Go
// backends despite their differing Unicode versions (Normalization Stability).

// UnicodeAssignedVersion / UnicodeAssignedSHA256 identify the embedded table.
const UnicodeAssignedVersion = "${UNICODE_VERSION}"
const UnicodeAssignedSHA256 = "${sha}"

type cpRange struct{ lo, hi rune }

// assignedRanges is sorted by lo; ranges are inclusive.
var assignedRanges = []cpRange{
${chunk(pairs, 6).map((r) => "\t" + r.join(", ") + ",").join("\n")}
}

// isAssignedCodePoint reports whether r is a Unicode scalar assigned as of
// Unicode ${UNICODE_VERSION}.
func isAssignedCodePoint(r rune) bool {
	lo, hi := 0, len(assignedRanges)-1
	for lo <= hi {
		mid := (lo + hi) / 2
		switch {
		case r < assignedRanges[mid].lo:
			hi = mid - 1
		case r > assignedRanges[mid].hi:
			lo = mid + 1
		default:
			return true
		}
	}
	return false
}
`;
  writeFileSync(resolve(ROOT, "canonical-go/unicode_assigned.go"), body);
}

function chunk(arr, n) {
  const out = [];
  for (let i = 0; i < arr.length; i += n) out.push(arr.slice(i, i + n));
  return out;
}

console.log("wrote: canonical/src/unicodeAssigned.ts, canonical-rs/src/unicode_assigned.rs, canonical-go/unicode_assigned.go");
