//! Byte-for-byte parity against the TypeScript reference golden vectors.
//!
//! Loads the committed `../canonical/vectors/golden.json` (generated by the TS
//! implementation) and independently recomputes every vector with this Rust
//! crate, asserting each recorded byte string / hash matches. A green run is
//! the parity evidence needed to promote the vectors from PRE-NORMATIVE to
//! NORMATIVE.

use std::collections::HashMap;

use paradigm_terra_canonical::addresses::address_to_bytes;
use paradigm_terra_canonical::domains;
use paradigm_terra_canonical::framing::encode_frame;
use paradigm_terra_canonical::hash::{domain_hash, sha256};
use paradigm_terra_canonical::integers::{encode_int256_dec, encode_uint256_dec, encode_uint64};
use paradigm_terra_canonical::jcs::{canonicalize_string, canonicalize_value, parse_canonical, JcsValue};
use paradigm_terra_canonical::merkle::{
    binary_merkle, state_root, stream_tree_root, StateNamespace, StreamLeaf,
};

const GOLDEN: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../canonical/vectors/golden.json"
));

fn hexp(bytes: &[u8]) -> String {
    format!("0x{}", hex::encode(bytes))
}

/// Accumulates per-field comparison failures across all vectors.
///
/// The fixture is parsed with this crate's own JCS parser (no JSON dependency);
/// the parser is itself exercised by the JCS parity vectors, so reading the
/// fixture this way is self-consistent.
struct Checker<'a> {
    mismatches: Vec<String>,
    checks: usize,
    by_id: HashMap<String, &'a JcsValue>,
}

impl<'a> Checker<'a> {
    fn new(vectors: &'a [JcsValue]) -> Self {
        let mut by_id = HashMap::new();
        for v in vectors {
            let id = v.get("id").and_then(JcsValue::as_str).expect("vector has id");
            by_id.insert(id.to_string(), v);
        }
        Checker {
            mismatches: Vec::new(),
            checks: 0,
            by_id,
        }
    }

    fn input(&self, id: &str) -> &'a JcsValue {
        self.by_id
            .get(id)
            .unwrap_or_else(|| panic!("missing vector {id}"))
            .get("input")
            .unwrap_or_else(|| panic!("vector {id} has no input"))
    }

    fn expect(&mut self, id: &str, field: &str, actual: &str) {
        self.checks += 1;
        let expected = self
            .by_id
            .get(id)
            .and_then(|v| v.get("output"))
            .and_then(|o| o.get(field))
            .and_then(JcsValue::as_str);
        match expected {
            Some(e) if e == actual => {}
            Some(e) => self
                .mismatches
                .push(format!("{id}.{field}\n    expected: {e}\n    actual:   {actual}")),
            None => self
                .mismatches
                .push(format!("{id}.{field}: field missing in golden.json")),
        }
    }
}

/// Read a required string field from a vector's `input` object.
fn input_str<'a>(input: &'a JcsValue, key: &str) -> &'a str {
    input
        .get(key)
        .and_then(JcsValue::as_str)
        .unwrap_or_else(|| panic!("missing input.{key}"))
}

#[test]
fn parity_with_typescript_golden_vectors() {
    let doc = parse_canonical(GOLDEN).expect("golden.json parses under restricted JCS");
    let vectors = doc
        .get("vectors")
        .and_then(JcsValue::as_array)
        .expect("vectors array");
    let mut c = Checker::new(vectors);

    // ---------- integers ----------
    for id in ["int256_zero", "int256_minus_one", "int256_min", "int256_max"] {
        let value = input_str(c.input(id), "value").to_string();
        let bytes = encode_int256_dec(&value).unwrap();
        c.expect(id, "bytes_hex", &hexp(&bytes));
        // sha256 is only recorded for the first two.
        if matches!(id, "int256_zero" | "int256_minus_one") {
            c.expect(id, "sha256", &hexp(&sha256(&bytes)));
        }
    }
    {
        let value = input_str(c.input("uint256_max"), "value").to_string();
        let bytes = encode_uint256_dec(&value).unwrap();
        c.expect("uint256_max", "bytes_hex", &hexp(&bytes));
    }
    {
        let value = input_str(c.input("uint64_sequence"), "value").to_string();
        let stripped = value.strip_prefix("0x").unwrap_or(&value);
        let n = u64::from_str_radix(stripped, 16).unwrap();
        c.expect("uint64_sequence", "bytes_hex", &hexp(&encode_uint64(n)));
    }

    // ---------- UTF-8 NFC ----------
    {
        let decomposed = "\u{0065}\u{0301}"; // e + combining acute
        let composed = "\u{00E9}";
        let nfc = paradigm_terra_canonical::strings::utf8_nfc_bytes(decomposed).unwrap();
        c.expect("utf8_nfc_e_acute", "bytes_hex", &hexp(&nfc));
        c.expect("utf8_nfc_e_acute", "sha256", &hexp(&sha256(&nfc)));
        let comp = paradigm_terra_canonical::strings::utf8_nfc_bytes(composed).unwrap();
        c.expect("utf8_nfc_e_acute", "composed_bytes_hex", &hexp(&comp));
    }

    // ---------- TON address ----------
    {
        let addr = input_str(c.input("ton_address_canonical"), "address").to_string();
        let bytes = address_to_bytes(&addr).unwrap();
        c.expect("ton_address_canonical", "address_bytes_hex", &hexp(&bytes));
        let hashed = domain_hash(domains::ADDRESS_V1, &bytes).unwrap();
        c.expect("ton_address_canonical", "domain_hash", &hexp(&hashed));
    }

    // ---------- JCS ----------
    {
        let json = input_str(c.input("jcs_sample_b2_a1"), "json").to_string();
        let canon = canonicalize_string(&json).unwrap();
        c.expect("jcs_sample_b2_a1", "canonical_utf8_hex", &hexp(&canon));
        c.expect(
            "jcs_sample_b2_a1",
            "canonical_text",
            std::str::from_utf8(&canon).unwrap(),
        );
        c.expect("jcs_sample_b2_a1", "sha256", &hexp(&sha256(&canon)));
    }
    {
        let expr = input_str(c.input("dsl_expr_gte_x_0"), "expression").to_string();
        let canon = canonicalize_string(&expr).unwrap();
        c.expect(
            "dsl_expr_gte_x_0",
            "canonical_text",
            std::str::from_utf8(&canon).unwrap(),
        );
        c.expect(
            "dsl_expr_gte_x_0",
            "dsl_v1_1_hash",
            &hexp(&domain_hash(domains::DSL_V1_1, &canon).unwrap()),
        );
        c.expect(
            "dsl_expr_gte_x_0",
            "dsl_v1_2_hash",
            &hexp(&domain_hash(domains::DSL_V1_2, &canon).unwrap()),
        );
    }
    {
        let json = input_str(c.input("jcs_big_integer"), "json").to_string();
        let canon = canonicalize_string(&json).unwrap();
        c.expect(
            "jcs_big_integer",
            "canonical_text",
            std::str::from_utf8(&canon).unwrap(),
        );
        c.expect("jcs_big_integer", "sha256", &hexp(&sha256(&canon)));
    }

    // ---------- CAL (canonicalize_value + domain hash) ----------
    {
        let cal = JcsValue::object(vec![
            ("action", JcsValue::string("wallet.send_ton")),
            (
                "agent_id",
                JcsValue::string(
                    "0:83dfd552e63729b472fc4e4a8f8f83d4a8f4f3a3e3e3a3e3e3a3e3e3a3e3e3a3",
                ),
            ),
            ("cal_version", JcsValue::string("0.1.0")),
            ("expiration_tick", JcsValue::int_u128(1_050_000)),
            ("nonce", JcsValue::int_u128(42)),
            (
                "preconditions",
                JcsValue::object(vec![
                    ("op", JcsValue::string("eq")),
                    ("lhs", JcsValue::object(vec![("var", JcsValue::string("x"))])),
                    ("rhs", JcsValue::object(vec![("const", JcsValue::int_u128(1))])),
                ]),
            ),
            ("receipt_required", JcsValue::Bool(true)),
        ]);
        let bytes = canonicalize_value(&cal).unwrap();
        c.expect(
            "cal_v1_hash_example",
            "canonical_text",
            std::str::from_utf8(&bytes).unwrap(),
        );
        c.expect(
            "cal_v1_hash_example",
            "cal_hash",
            &hexp(&domain_hash(domains::CAL_V1, &bytes).unwrap()),
        );
    }

    // ---------- Merkle: stream tree ----------
    {
        let root = stream_tree_root(&[
            StreamLeaf {
                stream_id: "treasury".into(),
                state_hash: [0xaa; 32],
                last_event_hash: [0xbb; 32],
                last_seqno: 100,
            },
            StreamLeaf {
                stream_id: "registry".into(),
                state_hash: [0x11; 32],
                last_event_hash: [0x22; 32],
                last_seqno: 7,
            },
        ])
        .unwrap();
        c.expect("merkle_stream_tree_2", "root", &hexp(&root));
    }

    // ---------- Merkle: 3 leaves, odd duplication ----------
    {
        let a = sha256(b"A");
        let b = sha256(b"B");
        let cc = sha256(b"C");
        let root = binary_merkle(&[a, b, cc], domains::MERKLE_NODE_V1).unwrap();
        c.expect("merkle_three_leaves_odd_duplicate", "root", &hexp(&root));
    }

    // ---------- State root (CAL Spec §7.3) ----------
    {
        let cv = |v: &JcsValue| canonicalize_value(v).unwrap();
        let empty_obj = || JcsValue::object(vec![]);
        let namespaces = vec![
            StateNamespace {
                name: "state.cal".into(),
                canonical_bytes: cv(&JcsValue::object(vec![
                    ("nonces", empty_obj()),
                    ("in_flight", empty_obj()),
                ])),
            },
            StateNamespace {
                name: "state.failure_mode".into(),
                canonical_bytes: cv(&JcsValue::object(vec![
                    ("current", JcsValue::string("NORMAL")),
                    ("entered_at", JcsValue::int_u128(0)),
                    ("recovery_progress", JcsValue::int_u128(0)),
                    ("is_bounded_mode", JcsValue::Bool(false)),
                    ("capture_guard_counters", empty_obj()),
                ])),
            },
            StateNamespace {
                name: "state.governance".into(),
                canonical_bytes: cv(&JcsValue::object(vec![
                    ("slots", empty_obj()),
                    ("active_proposals", JcsValue::array(vec![])),
                    ("cartel_flags", empty_obj()),
                    ("cluster_detection", empty_obj()),
                    ("proposal_votes", empty_obj()),
                    ("gas_price_nano_ptra_per_unit", JcsValue::int_u128(1000)),
                ])),
            },
            StateNamespace {
                name: "state.oracles".into(),
                canonical_bytes: cv(&JcsValue::object(vec![
                    ("nodes", empty_obj()),
                    ("feeds", empty_obj()),
                    ("slashed_nodes", empty_obj()),
                ])),
            },
            StateNamespace {
                name: "state.ptra".into(),
                canonical_bytes: cv(&JcsValue::object(vec![
                    ("total_supply", JcsValue::int_u128(1_000_000_000_000_000_000)),
                    ("burned_total", JcsValue::int_u128(0)),
                    ("burned_window", JcsValue::int_u128(0)),
                    ("twap_ton_ratio", JcsValue::int_u128(0)),
                    ("stakes", empty_obj()),
                    ("balances", empty_obj()),
                ])),
            },
            StateNamespace {
                name: "state.registry".into(),
                canonical_bytes: cv(&JcsValue::object(vec![
                    ("agents", empty_obj()),
                    (
                        "mcp_schema_hash",
                        JcsValue::string(&format!("0x{}", "00".repeat(32))),
                    ),
                    ("protocols", empty_obj()),
                ])),
            },
            StateNamespace {
                name: "state.tick".into(),
                canonical_bytes: cv(&JcsValue::object(vec![
                    ("current", JcsValue::int_u128(0)),
                    ("genesis", JcsValue::int_u128(0)),
                    ("blocks_per_tick", JcsValue::int_u128(12)),
                    ("epoch", JcsValue::int_u128(0)),
                ])),
            },
            StateNamespace {
                name: "state.treasury".into(),
                canonical_bytes: cv(&JcsValue::object(vec![
                    ("nav", JcsValue::int_u128(0)),
                    ("outflow_window", JcsValue::int_u128(0)),
                    ("developer_fund_balance", JcsValue::int_u128(0)),
                    ("staking_pool", JcsValue::int_u128(0)),
                    ("slot_pool", JcsValue::int_u128(0)),
                    ("collected_fees_window", JcsValue::int_u128(0)),
                ])),
            },
        ];
        let root = state_root(&namespaces).unwrap();
        c.expect("state_root_genesis_empty", "root", &hexp(&root));
        c.expect("state_root_genesis_empty", "domain_tag", domains::STATE_ROOT_V1);
    }

    // ---------- Framing ----------
    {
        let input = c.input("frame_hello");
        let type_tag =
            u16::from_str_radix(input_str(input, "type_tag").trim_start_matches("0x"), 16).unwrap();
        let version =
            u16::from_str_radix(input_str(input, "version").trim_start_matches("0x"), 16).unwrap();
        let payload = input_str(input, "payload_utf8").to_string();
        let frame = encode_frame(type_tag, version, payload.as_bytes()).unwrap();
        c.expect("frame_hello", "frame_hex", &hexp(&frame));
    }

    // ---------- Domain tag registry ----------
    for (name, value) in domains::ALL_DOMAIN_TAGS {
        let h = domain_hash(value, &[]).unwrap();
        c.expect(
            "domain_tags_registry",
            name,
            &format!("sha256(empty||tag)={}", hexp(&h)),
        );
    }

    // ---------- Report ----------
    if !c.mismatches.is_empty() {
        panic!(
            "{} of {} parity checks failed:\n\n{}",
            c.mismatches.len(),
            c.checks,
            c.mismatches.join("\n\n")
        );
    }
    println!("All {} parity checks passed against TypeScript golden vectors.", c.checks);
}
